### ISSUE TITLE
Update plugin to new backstage backend system

### ISSUE THREAD

**Issue by TheDukeDK** [codacy/backstage-plugin#2]
I am following your instructions to install the plugin. But step three(3) gives an error. I assume this is because I am using Backstage version 1.33.0 which supports the new backend system.

I tried to get around this with the following but it doesn't seem to work.

```
import scaffolderModuleCodacy from '@codacy/backstage-plugin';

// Codacy
backend.add(scaffolderModuleCodacy());
```

The step errors with.
```
2024-12-18T10:52:51.000Z Beginning step Add Repository to Codacy
49 2024-12-18T10:52:51.000Z Error: Failed to add repository to Codacy: Bad Request
50    at Object.handler (/home/tih@INTER-OLYMP.local/git/developer-experience/developer-portal-v2/node_modules/@codacy/backstage-plugin/src/actions/codacy.ts:38:15)
51    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
52    at async NunjucksWorkflowRunner.executeStep (/home/tih@INTER-OLYMP.local/git/developer-experience/developer-portal-v2/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:368:9)
53    at async NunjucksWorkflowRunner.execute (/home/tih@INTER-OLYMP.local/git/developer-experience/developer-portal-v2/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:504:9)
54    at async TaskWorker.runOneTask (/home/tih@INTER-OLYMP.local/git/developer-experience/developer-portal-v2/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:176:26)
55    at async run (/home/tih@INTER-OLYMP.local/git/developer-experience/developer-portal-v2/node_modules/p-queue/dist/index.js:163:29)
```

The action doesn't have a schema either.

![image](https://github.com/user-attachments/assets/41d5465a-d9f8-4aba-8e8e-c420418c4963)

**Comment by TheDukeDK** [comment]
Hmm, this might actually be working and it could just be a configuration issue. I know get the following a forbidden.

```
2024-12-18T11:10:14.000Z Beginning step Add Repository to Codacy
2024-12-18T11:10:15.000Z Error: Failed to add repository to Codacy: Forbidden

```
I created a token for a service account and am exporting this. is there some specific role the service user needs to have?

**Comment by TheDukeDK** [comment]
I tested the token by calling the api call with curl. This works.

```
curl -X POST https://app.codacy.com/api/v3/repositories \
  -H "Content-Type: application/json" \
  -H "api-token: $CODACY_API_TOKEN" \
  -d '{
    "repositoryFullPath": "my-org/my-repo",
    "provider": "gh"
  }'

```
So maybe its not picking up the config....

**Comment by TheDukeDK** [comment]
I figured it out and it works with the way(`hack`) that I added the backend.
